input {
  tcp {
    port => 5000
    codec => json_lines
  }
}

filter {
  if ![service] {
    mutate {
      add_field => { "service" => "unknown-service" }
    }
  }

  mutate {
    add_field => { "pipeline" => "bounty-logstash" }
  }
}

output {
  elasticsearch {
    hosts => ["${ELASTICSEARCH_HOSTS:http://elasticsearch:9200}"]
    index => "bounty-logs-%{[service]}-%{+YYYY.MM.dd}"
  }

  stdout {
    codec => json_lines
  }
}
